version: '3.2'
services:

  camera:
    image: ${REGISTRY}/duckietown/dt-ros-interface:ente-${ARCH}
    container_name: ros1-camera
    restart: unless-stopped
    network_mode: host
    pid: host
    environment:
      DT_LAUNCHER: sensor-camera
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  tof:
    image: ${REGISTRY}/duckietown/dt-ros-interface:ente-${ARCH}
    container_name: ros1-tof
    restart: unless-stopped
    network_mode: host
    environment:
      DT_LAUNCHER: sensor-tof
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  imu:
    image: ${REGISTRY}/duckietown/dt-ros-interface:ente-${ARCH}
    container_name: ros1-imu
    restart: unless-stopped
    network_mode: host
    environment:
      DT_LAUNCHER: sensor-imu
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  flight-controller:
    image: ${REGISTRY}/duckietown/dt-ros-interface:ente-${ARCH}
    container_name: ros1-flight-controller
    restart: unless-stopped
    network_mode: host
    environment:
      DT_LAUNCHER: flight-controller
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  ros:
    image: ${REGISTRY}/duckietown/dt-ros-commons:ente-${ARCH}
    container_name: ros1
    restart: unless-stopped
    network_mode: host
    volumes:
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  rosbridge-websocket:
    image: ${REGISTRY}/duckietown/dt-rosbridge-websocket:ente-${ARCH}
    container_name: ros1-rosbridge-websocket
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
