version: '3.2'
services:

  portainer:
    image: docker.io/duckietown/portainer:ente-${ARCH}
    container_name: portainer
    command: ["--host=unix:///var/run/docker.sock", "--no-auth"]
    restart: always
    network_mode: host
    volumes:
      - portainer-data:/data
      # docker socket
      - /var/run/docker.sock:/var/run/docker.sock

  dtps:
    image: ${REGISTRY}/duckietown/dtps-switchboard:release
    container_name: dtps
    restart: unless-stopped
    network_mode: host
    environment:
      RUST_LOG: "warn,dtps_http=debug"
    command: --tcp-port 11511 --tcp-host 0.0.0.0 --unix-path /dtps/switchboard.sock
    privileged: true
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  driver-tof:
    image: ${REGISTRY}/duckietown/dt-duckiebot-interface:ente-${ARCH}
    container_name: driver-tof
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      DT_SUPERUSER: 1
      DT_LAUNCHER: sensor-tof
    volumes:
      - /data:/data
      # dtps sockets
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  wifi-access-point:
    image: ${REGISTRY}/duckietown/dt-wifi-access-point:ente-${ARCH}
    container_name: wifi-access-point
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /data:/data
      # dtps sockets
      - /data/ramdisk/dtps:/dtps
      # host triggers
      - /triggers:/triggers
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

volumes:
  compose-data:
  portainer-data:
