version: '3.2'
services:

  portainer:
    image: docker.io/duckietown/portainer:ente-${ARCH}
    container_name: portainer
    command: ["--host=unix:///var/run/docker.sock", "--no-auth"]
    restart: always
    network_mode: host
    volumes:
      - portainer-data:/data
      # docker socket
      - /var/run/docker.sock:/var/run/docker.sock

  kvstore:
    image: ${REGISTRY}/duckietown/dt-kvstore:v0.2.0-${ARCH}
    container_name: kvstore
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      DT_SUPERUSER: 1
      DT_LAUNCHER: kv-store
    volumes:
      - /data:/data
      # dtps sockets
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

volumes:
  portainer-data:
